### ISSUE TITLE
stop working on windows 10

### ISSUE THREAD

**Issue by thepeppi** [OneB1t/HawaiiBiosReader#15]
think this is a bug and i can not find any answers about this
i have windows 10 installed and the program starts
then i open a bios and the program stops working

**Comment by OneB1t** [comment]
i use windows 10 without any issues ;) please provide more info or screenshots also provide bios you used

thanks

**Comment by lightningterror** [comment]
Perhaps an incompatible bios (Polaris/Vega) ?

**Comment by lightningterror** [comment]
Is this still an issue or can I close this ?
