### ISSUE TITLE
Asus R9290x-DC2-4GD5 support

### ISSUE THREAD

**Issue by LeonidEremin** [OneB1t/HawaiiBiosReader#2]
Hi, can you verify that program displays data correctly?
Everything looks sane except  PowerTable content. 
Bios link. 
http://www.techpowerup.com/vgabios/157203/asus-r9290x-4096-140407.html

**Comment by OneB1t** [comment]
its ok powertable content is only for visual control :D ill remove this in next itteration

**Comment by OneB1t** [comment]
its ok powertable content is only for visual control :D ill remove this in next itteration
