### ISSUE TITLE
Sapphire Radeon R9 290 Vapor-X 

### ISSUE THREAD

**Issue by Hagbrain** [OneB1t/HawaiiBiosReader#3]
Hi, 
first, Many thanks for your work!

I have a Problem with your HawaiiBiosReader cant read the Limit Tables, i tryed to set clocks to 1100/1500 with +100mV but dont work. (Only on Sapphire TriXX= Software)

This is my BIOS: https://www.techpowerup.com/vgabios/161499/sapphire-r9290x-4096-140416.html

GPU Freq Table: Reading Wrong
MEM Freq Table: Reading Wrong
All 4 Limit Tables: Reading Wrong

i hope u can fix the Limit Tables because DPM 1-7 cant read correctly (DPM 0 is reading correctly)

or u can make me a bios with 1100/1500 and +100mV :-*

Best regards Hagbrain

**Comment by Hagbrain** [comment]
ok +50mV also enough tested it, now how to write +50mV in the bios?

**Comment by OneB1t** [comment]
everything works as should please read guru3d or overclock.net forums for more info why there are such values :)
also its complicated to make +100mV bios without default vcore for your card which depends on ASIC quality (leakage)
