### ISSUE TITLE
Bonaire (R7 260X 2GB) support. Is it possible?

### ISSUE THREAD

**Issue by DaniloJacques** [OneB1t/HawaiiBiosReader#7]
Hi! Firstly I want to congratulate you for the project. It's awesome!

I have two Sapphire R7 260X, bonaire core. One of then have vram issue (sometimes when playing some "red lights" appears lol). To make this useful I'm building a little RIG to Zcash mining. I want to, if possibile, reduce voltage (to reduce power draw) and/or apply overclocked frequencies (to improve the performance). But when I submit the file to Hawaii Bios Editor the ROM is unsupported, with no changeable values. I attached the ROM file. There is hope to support this model?

[Bonaire.zip](https://github.com/OneB1t/HawaiiBiosReader/files/1048709/Bonaire.zip)

Thanks!

**Comment by mirh** [comment]
It was merged a week ago in #6. 
Compiling a new version should be enough to get it functioning.

**Comment by DaniloJacques** [comment]
@mirh Thanks!

**Comment by mirh** [comment]
You can close this.
