### ISSUE TITLE
Asus R7 360 Unsupported Rom

### ISSUE THREAD

**Issue by lightningterror** [OneB1t/HawaiiBiosReader#8]
Hello , I tried using the tool on my Asus r7 360 and it is listed in the supported gpus however I get the Unsupported  rom error.

Here is the bios file if it can help.
https://drive.google.com/open?id=0B8cQAq-Ko9-uN08takRpTVlPa1E

**Comment by mirh** [comment]
Same of #7 
EDIT: wtf is it me to be everywhere or you?

**Comment by lightningterror** [comment]
Both maybe?

Anyway
`string[] supportedDevIDs = new string[] { "67A0", "67A1", "67A2", "67A8", "67A9", "67AA", "67B0", "67B1", "67B9", "665C", "665D", "6658", "665F" };`

665F is the device id for the 360 and is already present in the code but I still get the error. I also tied to test with a 260 /260x bios and same issue.

**Comment by mirh** [comment]
Thing is
Latest release linked there is a year old. 

You have to compile newest version.

**Comment by lightningterror** [comment]
Actually I was compiling the build but I just noticed I was opening the wrong exe.
Seems there was an exe included in the source files and was just opening the included one and not the freshly compiled xD

**Comment by mirh** [comment]
Yet another reason not to include binaries in source control.
